stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-pack
      buildContext: .
      tag: lomo/test
      registry: registry.cn-hangzhou.aliyuncs.com
timeout: 60
