stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.5.0-jdk-8-alpine
      shellScript: mkdir ~/.m2 && cp updates/settings.xml ~/.m2/ && mvn clean package
        -Pprod
timeout: 60
