stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.5.0-jdk-8-alpine
      shellScript: mvn clean package -Pprod
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lomo/lion-dev
      registry: registry.cn-hangzhou.aliyuncs.com
timeout: 60
